/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCreditQueryClientResponse } from '../../models/page-response-credit-query-client-response';

export interface GetAllClientPaymentInformationByLastname$Params {
  page?: number;
  size?: number;
  lastname: string;
}

export function getAllClientPaymentInformationByLastname(http: HttpClient, rootUrl: string, params: GetAllClientPaymentInformationByLastname$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCreditQueryClientResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllClientPaymentInformationByLastname.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('lastname', params.lastname, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCreditQueryClientResponse>;
    })
  );
}

getAllClientPaymentInformationByLastname.PATH = '/credit-query/all-client/by/lastname';
