/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SendForRevisionRequest$Params {
  userId: number;
      body?: {
'description': string;
}
}

export function sendForRevisionRequest(http: HttpClient, rootUrl: string, params: SendForRevisionRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, sendForRevisionRequest.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    const formData = new FormData();
    formData.append('description', params.body?.description || '');
    rb.body(formData);
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

sendForRevisionRequest.PATH = '/credit-query/send/for-revision/{userId}';
