/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreditConditionResponse } from '../../models/credit-condition-response';

export interface GetConditionByName$Params {
  name: string;
}

export function getConditionByName(http: HttpClient, rootUrl: string, params: GetConditionByName$Params, context?: HttpContext): Observable<StrictHttpResponse<CreditConditionResponse>> {
  const rb = new RequestBuilder(rootUrl, getConditionByName.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreditConditionResponse>;
    })
  );
}

getConditionByName.PATH = '/credit-condition/condition/by/condition-name';
