services:
  postgres-bank:
    container_name: postgres_bank_db
    image: postgres
    environment:
      POSTGRES_USER: timur
      POSTGRES_PASSWORD: timur
      POSTGRES_DB: bank_db
    volumes:
      - postgres_bank:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bank-lending-net
    restart: unless-stopped

  postgres-rospassport:
    container_name: postgres_rospassport_db
    image: postgres
    environment:
      POSTGRES_USER: timur
      POSTGRES_PASSWORD: timur
      POSTGRES_DB: rospassport_db
    volumes:
      - postgres_rospassport:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - bank-lending-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - bank-lending-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mail_hog_am
    ports:
      - 1025:1025
      - 8025:8025

  backend:
    image: bank-lending-system-backend:latest
    container_name: bank-lending-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_BANK_URL: jdbc:postgresql://postgres-bank:5432/bank_db
      SPRING_DATASOURCE_BANK_USERNAME: timur
      SPRING_DATASOURCE_BANK_PASSWORD: timur
      SPRING_DATASOURCE_ROSPASSPORT_URL: jdbc:postgresql://postgres-rospassport:5432/rospassport_db
      SPRING_DATASOURCE_ROSPASSPORT_USERNAME: timur
      SPRING_DATASOURCE_ROSPASSPORT_PASSWORD: timur
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    ports:
      - 8088:8088
    depends_on:
      - postgres-bank
      - postgres-rospassport
      - mailhog
    networks:
      - bank-lending-net
    restart: unless-stopped

  frontend:
    image: bank-lending-system-frontend:latest
    container_name: bank-lending-ui
    ports:
      - 8080:80
    networks:
      - bank-lending-net
    depends_on:
      - backend

networks:
  bank-lending-net:
    driver: bridge

volumes:
  postgres_bank:
  postgres_rospassport:
  pgadmin: