services:
  postgres-bank:
    container_name: postgres_bank_db
    image: postgres
    environment:
      POSTGRES_USER: timur
      POSTGRES_PASSWORD: timur
      POSTGRES_DB: bank_db
    volumes:
      - postgres_bank:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bank-lending-net
    restart: unless-stopped

  postgres-rospassport:
    container_name: postgres_rospassport_db
    image: postgres
    environment:
      POSTGRES_USER: timur
      POSTGRES_PASSWORD: timur
      POSTGRES_DB: rospassport_db
    volumes:
      - postgres_rospassport:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - bank-lending-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - bank-lending-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mail_hog_am
    ports:
      - 1025:1025
      - 8025:8025


networks:
  bank-lending-net:
    driver: bridge

volumes:
  postgres_bank:
  postgres_rospassport:
  pgadmin: