/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCreditRequestResponseForDirector } from '../../models/page-response-credit-request-response-for-director';

export interface GetAllWithLendingOfficer$Params {
  page?: number;
  size?: number;
}

export function getAllWithLendingOfficer(http: HttpClient, rootUrl: string, params?: GetAllWithLendingOfficer$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCreditRequestResponseForDirector>> {
  const rb = new RequestBuilder(rootUrl, getAllWithLendingOfficer.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCreditRequestResponseForDirector>;
    })
  );
}

getAllWithLendingOfficer.PATH = '/credit-request/all-requests/with/lending-officer';
