INSERT INTO public.credit_request (loan_purpose, sum, immovable_property, movable_property,
                                   type, solvency_ref_path, employment_ref_path, is_processed,
                                   status, description_status, current_loans, created_date,
                                   last_modified_date, user_id, credit_condition_id, lending_officer_id)
VALUES ('Покупка недвижимости',
        400000,
        true,
        false,
        'HIRED_WORKERS',
        'uploads\1\1_2ndfl-example-2.pdf',
        'uploads\1\1_vipiska-test-2.pdf',
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        '{
            "срок кредита": 12,
            "ежемесячная оплата": 15000
        }'::jsonb,
        NOW(),
        NOW() + INTERVAL '1 day',
        1,
        5,
        5),

       ('Покупка автомобиля',
        1100000,
        false,
        true,
        'HIRED_WORKERS',
        'uploads\2\2_2ndfl-example-3.pdf',
        'uploads\2\2_vipiska-test-3.pdf',
        true,
        'REFUSED',
        'Невозможно выдать кредит данному клиенту, исходя из предложений банка',
        NULL,
        NOW(),
        NOW() + INTERVAL '1 day',
        2,
        NULL,
        5),

       ('Образование',
        650000,
        false,
        false,
        'HIRED_WORKERS',
        'uploads\3\1_2ndfl-example-4.pdf',
        'uploads\3\1_vipiska-test-4.pdf',
        true,
        'REFUSED',
        'Невозможно выдать кредит данному клиенту, исходя из предложений банка',
        '{
            "срок кредита": 6,
            "ежемесячная оплата": 20000
        }'::jsonb,
        NOW(),
        NOW() + INTERVAL '1 day',
        3,
        NULL,
        5),

       ('Покупка автомобиля',
        500000,
        false,
        true,
        'INDIVIDUAL_ENTREPRENEUR',
        'uploads\6\1_ip-dohod-1.pdf',
        NULL,
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        NULL,
        NOW(),
        NOW() + INTERVAL '1 day',
        6,
        5,
        5),

       ('Покупка недвижимости',
        2000000,
        true,
        false,
        'INDIVIDUAL_ENTREPRENEUR',
        'uploads\7\1_ip-dohod-2.pdf',
        NULL,
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        NULL,
        NOW(),
        NOW() + INTERVAL '1 day',
        7,
        3,
        5),

       ('Ремонт квартиры',
        1000000,
        true,
        false,
        'INDIVIDUAL_ENTREPRENEUR',
        'uploads\8\1_ip-dohod-3.pdf',
        NULL,
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        NULL,
        NOW(),
        NOW() + INTERVAL '1 day',
        8,
        3,
        5),

       ('Покупка мебели',
        300000,
        false,
        true,
        'INDIVIDUAL_ENTREPRENEUR',
        'uploads\9\1_ip-dohod-4.pdf',
        NULL,
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        NULL,
        NOW(),
        NOW() + INTERVAL '1 day',
        9,
        5,
        5),

       ('Лечение',
        50000,
        false,
        false,
        'INDIVIDUAL_ENTREPRENEUR',
        'uploads\10\1_ip-dohod-5.pdf',
        NULL,
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        NULL,
        NOW(),
        NOW() + INTERVAL '1 day',
        10,
        8,
        5),

       ('Покупка недвижимости',
        400000,
        true,
        false,
        'INDIVIDUAL_ENTREPRENEUR',
        'uploads\11\1_ip-dohod-6.pdf',
        NULL,
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        '{
            "срок кредита": 12,
            "ежемесячная оплата": 15000
        }'::jsonb,
        NOW(),
        NOW() + INTERVAL '1 day',
        11,
        5,
        5),

       ('Покупка недвижимости',
        750000,
        true,
        true,
        'INDIVIDUAL_ENTREPRENEUR',
        'uploads\12\1_ip-dohod-7.pdf',
        NULL,
        true,
        'APPROVED',
        'Ваш кредитный запрос был одобрен, для продолжения проверьте почту',
        NULL,
        NOW(),
        NOW() + INTERVAL '1 day',
        12,
        3,
        5);