/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientInformationResponse } from '../../models/client-information-response';

export interface GetClientInfoBySerialNumber$Params {
  serialNum: string;
}

export function getClientInfoBySerialNumber(http: HttpClient, rootUrl: string, params: GetClientInfoBySerialNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientInformationResponse>> {
  const rb = new RequestBuilder(rootUrl, getClientInfoBySerialNumber.PATH, 'get');
  if (params) {
    rb.query('serialNum', params.serialNum, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientInformationResponse>;
    })
  );
}

getClientInfoBySerialNumber.PATH = '/client-information/client/by/serial-number';
