/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseClientInformationResponse } from '../../models/page-response-client-information-response';

export interface GetAllClientInfoBySort$Params {
  page?: number;
  size?: number;
  isAsc: boolean;
}

export function getAllClientInfoBySort(http: HttpClient, rootUrl: string, params: GetAllClientInfoBySort$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseClientInformationResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllClientInfoBySort.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('isAsc', params.isAsc, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseClientInformationResponse>;
    })
  );
}

getAllClientInfoBySort.PATH = '/client-information/all-client/by/sort';
