/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreditRequestClientResponse {
  descriptionStatus?: string;
  id?: number;
  loanPurpose?: string;
  status?: 'APPROVED' | 'REFUSED' | 'UNDER_CONSIDERATION' | 'SENT_FOR_REVISION';
  sum?: number;
}
