/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreditQueryTaxAgentHiredWorkerRequest {
  inn: string;
  kpp: string;
  name: string;
}
