/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreditQueryClientResponse {
  firstName?: string;
  id?: number;
  immovableProperty?: boolean;
  inn?: string;
  kpp?: string;
  lastName?: string;
  monthlyPayment?: string;
  movableProperty?: boolean;
  name?: string;
  surName?: string;
  taxCalculationAmount?: string;
  totalIncome?: string;
}
