/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreditRequestResponseForDirector {
  clientFirstName?: string;
  clientLastName?: string;
  clientSurName?: string;
  date?: string;
  id?: number;
  lendingOfficerFirstName?: string;
  lendingOfficerLastName?: string;
  lendingOfficerSurName?: string;
  status?: 'APPROVED' | 'REFUSED' | 'UNDER_CONSIDERATION' | 'SENT_FOR_REVISION';
}
