/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginChangeRequest {
  confirmNewPassword: string;
  email: string;
  newPassword: string;
  oldPassword: string;
}
