/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditQueryClientResponse } from '../models/credit-query-client-response';
export interface PageResponseCreditQueryClientResponse {
  content?: Array<CreditQueryClientResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
