/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditRequestResponse } from '../models/credit-request-response';
export interface PageResponseCreditRequestResponse {
  content?: Array<CreditRequestResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
