/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientInformationResponse } from '../models/client-information-response';
export interface PageResponseClientInformationResponse {
  content?: Array<ClientInformationResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
