/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditRequestClientResponse } from '../models/credit-request-client-response';
export interface PageResponseCreditRequestClientResponse {
  content?: Array<CreditRequestClientResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
