/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditRequestResponseForDirector } from '../models/credit-request-response-for-director';
export interface PageResponseCreditRequestResponseForDirector {
  content?: Array<CreditRequestResponseForDirector>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
