spring:
  datasource:
    bank:
      url: jdbc:postgresql://localhost:5432/bank_db
      username: timur
      password: timur
      driver-class-name: org.postgresql.Driver
    rospassport:
      url: jdbc:postgresql://localhost:5433/rospassport_db
      username: timur
      password: timur
      driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.PostgreSQLDialect

#  liquibase:
#    enabled: true

  mail:
    port: 1025
    host: localhost
    username:
    password:
    protocol: smtp

auth:
  token:
    jwt-secret: PE+01rgtPbv1Xr4JxgTwcB2oB+m+4NZVD+SO+WBiudE=
    expiration: 36000000 # 10 часов


server:
  port: 8088
